sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3 # needed for native src android compile
  - build-tools-28.0.3
  - android-23
  - android-27 # needed for native src android compile
  - android-28
  - extra-android-m2repository
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - ".nvm"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- echo no | npm install -g nativescript
- tns usage-reporting disable
- tns error-reporting disable
- echo no | npm install -g grunt-cli
- npm install
- grunt compile
matrix:
  include:
  - stage: lint
    language: android
    jdk: oraclejdk8
    os: linux
    before_install: nvm install 8.11.3
    script: grunt lint
  - stage: build
    language: android
    os: linux
    env:
    - Android="28"
    jdk: oraclejdk8
    before_install: nvm install 8.11.3
    script: grunt ci:build:android
  - stage: build
    os: osx
    env:
    - iOS="11.4"
    - Xcode="9.4"
    osx_image: xcode9.4
    language: node_js
    node_js: '8'
    jdk: oraclejdk8
    before_install:
    - pip install --upgrade pip
    - pip install --user --upgrade matplotlib
    - pip install six
    script: grunt ci:build:ios
  - stage: webpack
    language: android
    os: linux
    env:
    - Android="28"
    - Platform="Android"
    jdk: oraclejdk8
    before_install: nvm install 8.11.3
    script: grunt ci:webpack:android
  - stage: webpack
    os: osx
    env:
    - iOS="11.4"
    - Xcode="9.4"
    - Platform="iOS"
    osx_image: xcode9.4
    language: node_js
    node_js: '8'
    jdk: oraclejdk8
    before_install:
    - pip install --upgrade pip
    - pip install --user --upgrade matplotlib
    - pip install six
    script: grunt ci:webpack:ios
  - stage: deploy
    if: branch = release
    language: android
    jdk: oraclejdk8
    os: linux
    before_install: nvm install 8.11.3
    script: skip
    before_deploy:
    - cd bin/dist
    deploy:
      provider: npm
      email: peter@tangrasoft.com
      api_key:
        secure: "RCLcaUTXyRy6CxKdYaCzGkw6F5utJ/pTHDBMlzkBIa8j1XXDRC9PDBK7giKd1p5w69yEvMWYzv5MVfheAzwPfV5gAycnfi/ABoOqFnB58O4PXNWqT2cQ8Ge2dQ8BSU+FJLCMEICqR4fK9QK2wjTNoos6xOWVrqgMsA7ttS9pgCheI7pAF+xb4X0WTh7JoG0LoS0d2pbImWBVN4VC2D570bYo2LEQvoL76lWaovxNyHLcROj5C8JZqsIqcxHsX2SZGzcZYuUyV6Anjk0u6Lb/rfZVaKOdTYSFqN14+a4logcaeMotpYSQcGa/ThnzrItAT9onCJOGHSnXaCYFDysmkOFvp3mYDQylAm773zbvyT7qLq0qPr3TMVTbjXw7qUA0SVtFw7FfoX8r8eicTfdnNObsYVf+t22aCQKVMTxqjMxTVecbxmHdmmEceM7YF9A9P9u9Yvqs5e/tzBSu+tkmYCfLUhLlx+wTNjhi5B+MDXFu9byfkesbJVCtYW/Pc5L/PYyix5Vka5Gf/Tsn8Vegldz3oL9AZUqugzFBWzj6VqoU5TQR7+X1IBjn2Q/ATJyNoGgMGmiwbFsZxEB1193ujQ8TTP44baaaLpOL9WJyxFkbsLiwr0vHI8WbtysD/ZAdt0K+hos6GIYKP6jUQiDQK9qLgUKIwBpldNsk8Xi75aU="
      skip_cleanup: true
      on:
        branch: release
